function MakeMP4_ffmpeg(frameStart, frameEnd, frameDir, movieFPS)
    range = [frameStart,frameEnd];
    
    [~,name] = fileparts(frameDir);
    if (isempty(name))
        name = 'movie';
    end
    
    ffmpegimages2video(fullfile(frameDir,'%04d.tif'),...
        fullfile(frameDir,[name,'.mp4']),...
        'InputFrameRate',movieFPS,...
        'InputStartNumber',range,...
        'x264Tune','stillimage',...
        'OutputFrameRate',movieFPS);
end
