% This is just a big list of names and associated extensions supported by bioformats; based on their website:
% https://www.openmicroscopy.org/site/support/bio-formats5.1/supported-formats.html.

function formats = GetSupportedFormats()
    extensions = {{'.gif'};
                {'.jpg'};
                {'.jp2'};
                {'.png'};
                {'.txt'};
                {'.tif';'.tiff'};
                {'.bmp'};
                
                {'.sld'};
                {'.tif'};
                {'.aim'};
                {'.al3d'};
                {'.gel'};
                {'.am';'.amiramesh';'.grey';'.hx';'.labels'};
                {'.cif'};
                {'.img';'.hdr'};
                {'.png'};
                {'.afi';'.svs'};
                {'.svs'};
                {'.htd';'.pnl'};
                {'.avi'};
                {'.arf'};
                {'.exp';'.tif'};
                {'.sdt'};
                {'.1sc'};
                {'.pic';'.raw';'.xml'};
                {'.scn'};
                {'.ims'};
                { };
                {'.img'};
                {'.cr2';'.crw'};
                {'.ch5'};
                {'.c01';'.dib'};
                {'.vsi'};
                {'.xml';'.tif'};
                {'.dv';'.r3d'};
                {'.dcm';'.dicom'};
                {'.v'};
                {'.eps';'.epsi';'.ps'};
                {'.flex';'.mea';'.res'};
                {'.img'};
                {'.tiff'};
                {'.fits'};
                {'.dm3';'.dm4'};
                {'.dm2'};
                {'.naf'};
                {'.his'};
                {'.ndpi';'.ndpis'};
                {'.vms'};
                {'.txt';'.tif';'.bmp';'.jpg'};
                {'.i2i'};
                {'.ics';'.ids'};
                {'.fff'};
                {'.seq'};
                {'.ipw'};
                {'.hed';'.img'};
                {'.mod'};
                {'.liff'};
                {'.raw'};
                {'.tif'};
                {'.obf';'.msr'};
                {'.xdce';'.tif'};
                {'.frm'};
                {'.inr'};
                {'.hdr'};
                {'.ipl'};
                {'.ipm'};
                {'.dat';'.img';'.par'};
                {'.jpk'};
                {'.jpx'};
                {'.xv'};
                {'.bip'};
                {'.fli'};
                {'.msr'};
                {'.lei';'.tif'};
                {'.lif'};
                {'.scn'};
                {'.sxm'};
                {'.l2d';'.tif';'.scn'};
                {'.lim'};
                {'.tiff'};
                {'.stk';'.nd'};
                {'.tif'};
                {'.tif';'.txt';'.xml'};
                {'.mnc'};
                {'.mrw'};
                {'.mng'};
                {'.stp'};
                {'.mrc'};
                {'.nef';'.tif'};
                {'.img';'.hdr'};
                {'.tiff'};
                {'.tiff'};
                {'.nd2'};
                {'.nrrd';'.nhdr';'.raw';'.txt'};
                {'.apl';'.mtb';'.tnb';'.tif';'.obsep'};
                {'.oib';'.oif'};
                {'.tif'};
                {'.xml';'.dat';'.tif'};
                {'.tiff'};
                {'.ome.tiff'};
                {'.ome';'.ome.xml'};
                {'.top'};
                {'.pcoraw';'.rec'};
                {'.pcx'};
                {'.pds'};
                {'.im3'};
                {'.tiff';'.xml'};
                {'.tif';'.2';'.3';'.4'};
                {'.pbm';'.pgm';'.ppm'};
                {'.psd'};
                {'.tif';'.tiff'};
                {'.bin'};
                {'.pict'};
                {'.tif';'.xml';'.cfg'};
                {'.afm'};
                {'.mov'};
                {'.sm2';'.sm3'};
                { };
                {'.xqd';'.xqf'};
                {'.cxd'};
                {'.tiff'};
                { };
                {'.spi';'.stk'};
                {'.tga'};
                {'.vws'};
                {'.tfr';'.ffr';'.zfr';'.zfp';'.2fl'};
                {'.tif';'.sld';'.jpg'};
                {'.pr3'};
                {'.dat';'.hdr'};
                {'.fdf'};
                {'.hdf'};
                {'.dti'};
                {'.xys';'.html'};
                {'.mvd2'};
                {'.acff'};
                {'.wat'};
                {'.wlz'};
                {'.lms'};
                {'.xml';'.tiff'};
                {'.zvi'};
                {'.czi'};
                {'.lsm';'.mdb'}};
            
            names = {'GIF (Graphics Interchange Format)';
                'JPEG';
                'JPEG 2000';
                'PNG (Portable Network Graphics)';
                'Text';
                'TIFF (Tagged Image File Format)';
                'Windows Bitmap';
                
                '3i SlideBook';
                'Andor Bio-Imaging Division (ABD) TIFF';
                'AIM';
                'Alicona 3D';
                'Amersham Biosciences Gel';
                'Amira Mesh';
                'Amnis FlowSight';
                'Analyze 7.5';
                'Animated PNG';
                'Aperio AFI';
                'Aperio SVS TIFF';
                'Applied Precision CellWorX';
                'AVI (Audio Video Interleave)';
                'Axon Raw Format';
                'BD Pathway';
                'Becker & Hickl SPCImage';
                'Bio-Rad Gel';
                'Bio-Rad PIC';
                'Bio-Rad SCN';
                'Bitplane Imaris';
                'Bruker MRI';
                'Burleigh';
                'Canon DNG';
                'CellH5';
                'Cellomics';
                'cellSens VSI';
                'CellVoyager';
                'DeltaVision';
                'DICOM';
                'ECAT7';
                'EPS (Encapsulated PostScript)';
                'Evotec/PerkinElmer Opera Flex';
                'FEI';
                'FEI TIFF';
                'FITS (Flexible Image Transport System)';
                'Gatan Digital Micrograph';
                'Gatan Digital Micrograph 2';
                'Hamamatsu Aquacosmos NAF';
                'Hamamatsu HIS';
                'Hamamatsu ndpi';
                'Hamamatsu VMS';
                'Hitachi S-4800';
                'I2I';
                'ICS (Image Cytometry Standard)';
                'Imacon';
                'ImagePro Sequence';
                'ImagePro Workspace';
                'IMAGIC';
                'IMOD';
                'Improvision Openlab LIFF';
                'Improvision Openlab Raw';
                'Improvision TIFF';
                'Imspector OBF';
                'InCell 1000/2000';
                'InCell 3000';
                'INR';
                'Inveon';
                'IPLab';
                'IVision';
                'JEOL';
                'JPK';
                'JPX';
                'Khoros VIFF (Visualization Image File Format) Bitmap';
                'Kodak BIP';
                'Lambert Instruments FLIM';
                'LaVision Imspector';
                'Leica LCS LEI';
                'Leica LAS AF LIF (Leica Image File Format)';
                'Leica SCN';
                'LEO';
                'Li-Cor L2D';
                'LIM (Laboratory Imaging/Nikon)';
                'MetaMorph 7.5 TIFF';
                'MetaMorph Stack (STK)';
                'MIAS (Maia Scientific)';
                'Micro-Manager';
                'MINC MRI';
                'Minolta MRW';
                'MNG (Multiple-image Network Graphics)';
                'Molecular Imaging';
                'MRC (Medical Research Council)';
                'NEF (Nikon Electronic Format)';
                'NIfTI';
                'Nikon Elements TIFF';
                'Nikon EZ-C1 TIFF';
                'Nikon NIS-Elements ND2';
                'NRRD (Nearly Raw Raster Data)';
                'Olympus CellR/APL';
                'Olympus FluoView FV1000';
                'Olympus FluoView TIFF';
                'Olympus ScanR';
                'Olympus SIS TIFF';
                'OME-TIFF';
                'OME-XML';
                'Oxford Instruments';
                'PCORAW';
                'PCX (PC Paintbrush)';
                'Perkin Elmer Densitometer';
                'PerkinElmer Nuance';
                'PerkinElmer Operetta';
                'PerkinElmer UltraVIEW';
                'Portable Any Map';
                'Adobe Photoshop PSD';
                'Photoshop TIFF';
                'PicoQuant Bin';
                'PICT (Macintosh Picture)';
                'Prairie Technologies TIFF';
                'Quesant';
                'QuickTime Movie';
                'RHK';
                'SBIG';
                'Seiko';
                'SimplePCI & HCImage';
                'SimplePCI & HCImage TIFF';
                'SM Camera';
                'SPIDER';
                'Targa';
                'TillPhotonics TillVision';
                'Topometrix';
                'Trestle';
                'UBM';
                'Unisoku';
                'Varian FDF';
                'Veeco AFM';
                'VG SAM';
                'VisiTech XYS';
                'Volocity';
                'Volocity Library Clipping';
                'WA-TOP';
                'Woolz';
                'Zeiss Axio CSM';
                'Zeiss AxioVision TIFF';
                'Zeiss AxioVision ZVI (Zeiss Vision Image)';
                'Zeiss CZI';
                'Zeiss LSM (Laser Scanning Microscope) 510/710'};

	formats = [names extensions];
end
